import { PlatformService } from 'terminus-core'
import { isChineseLocale } from '../utils/locale-helper'

type Bilingual = { en: string, zh: string }

let currentIsZh = false

const CloudSyncLang = {
    lang: {
        common: {
            menu_title: { en: 'Tabby Sync Selective', zh: 'Tabby 选择性同步' },
            verifyConfigString: 'This file is generated by Tabby Sync Selective Plugin',
            config_inject_header: '/*This file is generated by Tabby Sync Selective Plugin - DO NOT MODIFY THIS FILE DIRECTLY OTHERWISE PLUGIN WILL NOT WORK PROPERLY*/\n',
            errors: {
                invalidServerConfig: {
                    en: 'Server contains invalid Tabby settings or empty.',
                    zh: '云端配置无效或为空。',
                },
            },
        },
        tabs: {
            general: { en: 'General', zh: '常规' },
            sync_settings: { en: 'Sync Settings', zh: '同步设置' },
            feedback: { en: 'Feedback', zh: '反馈' },
            support_us: { en: 'Support Us', zh: '支持我们' },
            change_logs: { en: 'Change Logs', zh: '更新日志' },
            check_for_update: { en: 'Check for update', zh: '检查更新' },
            logs: { en: 'Logs', zh: '日志' },
        },
        form: {
            error: {
                required_all: {
                    en: 'Please fill in all fields',
                    zh: '请填写所有字段',
                },
            },
        },
        settings: {
            title: { en: 'Cloud Sync Setting', zh: '云同步设置' },
            sub_title: {
                en: 'Here you could login to your cloud account and sync the settings across devices.',
                zh: '在此登录云账户，并在多台设备间同步 Tabby 配置。',
            },
            service_label: { en: 'Services', zh: '云服务' },
            amazon: {
                connected: 'Cloud Service Connected!',
                save_settings_failed: 'An error occurred when trying to save config.',
                save_settings_success: 'Your settings is saved.',
            },
            error_connection_timeout: 'Connection timed out.',
        },
        sync: {
            loading_config: { en: 'Loading config...', zh: '正在加载配置...' },
            sync_confirmation: {
                en: 'We found cloud setting. Please choose the sync direction!',
                zh: '检测到云端配置，请选择同步方向！',
            },
            setting_valid: { en: 'Your setting is valid.', zh: '配置验证通过。' },
            error_setting_save_file: 'Connect Ok. But unable to write file at this location!',
            error_connection: {
                en: 'Unable to connect with your settings',
                zh: '无法使用当前配置连接',
            },
            error_invalid_setting: 'Your setting cloud file contains invalid settings. Local file synced up instead!',
            error_invalid_setting_2: 'Your sync config is invalid. Please re-configure it!',
            error_save_setting: 'Something wrong! unable to save settings.',
            need_to_save_config: 'Please save your config first',
            sync_success: 'Your saved settings was synced.',
            sync_error: 'Unable to sync your setting. Please check the configuration!',
            sync_server_failed: 'Sync file to the cloud failed. Please check your cloud service!',
            sync_enabled: 'Sync feature enabled.',
            sync_disabled: 'Sync feature disabled.',
            confirm_remove_setting: 'Are you sure want to remove saved config?',
            remove_setting_success: 'Your settings had been removed.',
            remove_setting_error: 'Can not remove your setting. Try again later!',
            setting_changes_saved: 'Your setting changes had been saved.',
            sync_sections_saved: {
                en: 'Sync settings saved.',
                zh: '同步设置已保存。',
            },
            sync_mode_full: {
                en: 'Full overwrite',
                zh: '全量覆盖',
            },
            sync_mode_full_desc: {
                en: 'Replace the entire config.yaml. Best for two machines with the same OS.',
                zh: '整文件覆盖 config.yaml，适合两台相同系统的设备。',
            },
            sync_mode_platform_safe: {
                en: 'Cross-platform',
                zh: '跨平台同步',
            },
            sync_mode_platform_safe_desc: {
                en: 'Skip hotkeys, fonts, shell paths and other platform-specific settings.',
                zh: '自动排除热键、字体、shell 路径等平台相关设置。',
            },
            sync_mode_custom: {
                en: 'Custom',
                zh: '自定义',
            },
            sync_mode_custom_desc: {
                en: 'Pick individual settings to sync in a separate dialog.',
                zh: '在弹窗中自由选择需要同步的配置项。',
            },
            sync_mode_selective: {
                en: 'Cross-platform (exclude platform-specific settings)',
                zh: '跨平台（排除平台相关设置）',
            },
            sync_sections_title: { en: 'Sync settings', zh: '同步设置' },
            sync_sections_hint: {
                en: 'Cross-platform mode skips hotkeys, fonts, shell paths and other platform-specific items. Custom mode lets you pick each item.',
                zh: '跨平台模式会跳过热键、字体、shell 路径等平台相关项；自定义模式可逐项选择。',
            },
            manual_sync_title: { en: 'Choose sections to sync', zh: '选择本次同步范围' },
            manual_sync_confirm: { en: 'Start sync', zh: '开始同步' },
            custom_fields_title: { en: 'Custom sync items', zh: '自定义同步项' },
            custom_fields_hint: {
                en: 'Select which config fields should be included when using Custom mode.',
                zh: '选择在「自定义」模式下需要同步的配置项。',
            },
            configure_custom_items: { en: 'Configure sync items', zh: '配置同步项' },
            custom_fields_summary: {
                en: '{count} of {total} items selected',
                zh: '已选择 {count} / {total} 项',
            },
            save_sync_settings: { en: 'Save sync settings', zh: '保存同步设置' },
        },
        log: {
            invalid_cloud_settings: 'Invalid cloud settings syncing',
            read_cloud_settings: 'Reading cloud settings',
            error_upload_settings: 'Upload settings file from local',
            error_test_connection: 'Connection error.',
        },
        s3: {
            title: 'Enter your AppID and Secret token',
            title_blackblaze: 'Enter your KeyID and Application Key',
            app_id_placeholder: 'Application Id',
            app_secret_placeholder: 'Application Secret',
            blackblaze_key_placeholder: 'Your Key ID',
            blackblaze_app_key_placeholder: 'Your Application Key Id',
            bucket_placeholder: 'Bucket',
            region_placeholder: 'Default region (optional)',
            blackblaze_bucket_placeholder: 'Enter your BlackBlaze B2 region',
            endpoint_placeholder: 'Endpoint URL',
            location_placeholder: 'Location /',
        },
        ftp: {
            title: 'Enter your FTP login credentials',
            host_placeholder: 'Host',
            location_placeholder: 'Location /',
            username_placeholder: 'Username',
            password_placeholder: '******',
            port_placeholder: 'Port',
        },
        webdav: {
            title: 'Enter your WebDav login credentials',
            host_placeholder: 'Host',
            username_placeholder: 'Username or Email',
            password_placeholder: '******',
            port_placeholder: 'Port',
            location_placeholder: 'Location /',
        },
        gist: {
            title: "Enter your Gist credentials",
            name: 'Friendly name (optional)',
            id: 'Gist ID (Leave empty to create a new one)',
            token: 'Gist token',
            invalid_provider: 'Invalid service provider.',
            enter_id: 'Enter your Gist ID',
            error_create_gist: 'Unable to create new gist. Check your token permission!',
        },
        buttons: {
            sync_from_cloud: 'Sync Cloud Settings',
            sync_from_local: 'Upload Local Settings',
            check_update: 'Check for updates',
            yes: 'Yes',
            cancel: { en: 'Cancel', zh: '取消' },
            no: 'No',
            ok: { en: 'OK', zh: '确定' },
            view: 'View',
            test_connection: 'Test Connection',
            processing: 'Processing...',
            save_settings: 'Save This Setting',
            upload_settings: 'Upload Local Setting (Forced)',
            cloud_syncing_progress: 'Syncing with the cloud...',
            remove_saved_setting: 'Remove this setting',
        },
    },

    refreshLocale (platform: PlatformService): void {
        currentIsZh = isChineseLocale(platform)
    },

    isChinese (): boolean {
        return currentIsZh
    },

    trans: (key: string, vars?: Record<string, string | number>): string => {
        let dict: any = CloudSyncLang.lang
        const objects = key.split('.')
        for (const i in objects) {
            if (typeof dict[objects[i]] !== 'undefined') {
                dict = dict[objects[i]]
            }
        }

        let text = ''
        if (typeof dict === 'string') {
            text = dict
        } else if (dict && typeof dict.en === 'string' && typeof dict.zh === 'string') {
            text = currentIsZh ? dict.zh : dict.en
        }

        if (vars) {
            for (const [name, value] of Object.entries(vars)) {
                text = text.replace(`{${name}}`, String(value))
            }
        }

        return text
    },
}

export default CloudSyncLang
