import { ConfigService, PlatformService } from 'terminus-core'
import { isChineseLocale } from '../utils/locale-helper'

type Bilingual = { en: string, zh: string }

let currentIsZh = false

const CloudSyncLang = {
    lang: {
        common: {
            menu_title: { en: 'Tabby Sync Selective', zh: 'Tabby 选择性同步' },
            details: { en: 'Details', zh: '详细说明' },
            verifyConfigString: 'This file is generated by Tabby Sync Selective Plugin',
            config_inject_header: '/*This file is generated by Tabby Sync Selective Plugin - DO NOT MODIFY THIS FILE DIRECTLY OTHERWISE PLUGIN WILL NOT WORK PROPERLY*/\n',
            errors: {
                invalidServerConfig: {
                    en: 'Server contains invalid Tabby settings or empty.',
                    zh: '云端配置无效或为空。',
                },
            },
        },
        tabs: {
            general: { en: 'General', zh: '常规' },
            sync_settings: { en: 'Sync Settings', zh: '同步设置' },
            feedback: { en: 'Feedback', zh: '反馈' },
            support_us: { en: 'Support Us', zh: '支持我们' },
            change_logs: { en: 'Change Logs', zh: '更新日志' },
            check_for_update: { en: 'Check for update', zh: '检查更新' },
            logs: { en: 'Logs', zh: '日志' },
        },
        form: {
            error: {
                required_all: {
                    en: 'Please fill in all fields',
                    zh: '请填写所有字段',
                },
            },
        },
        settings: {
            title: { en: 'Cloud Sync Setting', zh: '云同步设置' },
            sub_title: {
                en: 'Here you could login to your cloud account and sync the settings across devices.',
                zh: '在此登录云账户，并在多台设备间同步 Tabby 配置。',
            },
            service_label: { en: 'Services', zh: '云服务' },
            amazon: {
                connected: 'Cloud Service Connected!',
                save_settings_failed: 'An error occurred when trying to save config.',
                save_settings_success: 'Your settings is saved.',
            },
            error_connection_timeout: 'Connection timed out.',
        },
        sync: {
            loading_config: { en: 'Loading config...', zh: '正在加载配置...' },
            sync_confirmation: {
                en: 'We found cloud setting. Please choose the sync direction!',
                zh: '检测到云端配置，请选择同步方向！',
            },
            setting_valid: { en: 'Your setting is valid.', zh: '配置验证通过。' },
            error_setting_save_file: 'Connect Ok. But unable to write file at this location!',
            error_connection: {
                en: 'Unable to connect with your settings',
                zh: '无法使用当前配置连接',
            },
            error_invalid_setting: 'Your setting cloud file contains invalid settings. Local file synced up instead!',
            error_invalid_setting_2: 'Your sync config is invalid. Please re-configure it!',
            error_save_setting: 'Something wrong! unable to save settings.',
            need_to_save_config: 'Please save your config first',
            sync_success: 'Your saved settings was synced.',
            sync_error: 'Unable to sync your setting. Please check the configuration!',
            sync_server_failed: 'Sync file to the cloud failed. Please check your cloud service!',
            sync_enabled: 'Sync feature enabled.',
            sync_disabled: 'Sync feature disabled.',
            confirm_remove_setting: 'Are you sure want to remove saved config?',
            remove_setting_success: 'Your settings had been removed.',
            remove_setting_error: 'Can not remove your setting. Try again later!',
            setting_changes_saved: 'Your setting changes had been saved.',
            sync_sections_saved: {
                en: 'Sync settings saved.',
                zh: '同步设置已保存。',
            },
            sync_mode_full: {
                en: 'Full sync',
                zh: '全量同步',
            },
            sync_mode_full_desc: {
                en: 'Sync all tracked settings. Merges into the shared cloud config; other devices can still use Cross-platform or Custom.',
                zh: '同步所有已跟踪的设置项，合并写入云端共享配置；其他设备仍可使用跨平台或自定义模式。',
            },
            sync_mode_compat_note: {
                en: 'All three modes share one cloud file. Each device only reads/writes its own field subset; Full uploads do not block Cross-platform or Custom downloads.',
                zh: '三种模式共用同一份云端配置。各设备只读写自己选中的字段；Mac 全量上传后，Windows 跨平台模式仍可正常同步。',
            },
            sync_mode_platform_safe: {
                en: 'Cross-platform',
                zh: '跨平台同步',
            },
            sync_mode_platform_safe_desc: {
                en: 'Skip hotkeys, fonts, shell paths and other platform-specific settings.',
                zh: '自动排除热键、字体、shell 路径等平台相关设置。',
            },
            sync_mode_custom: {
                en: 'Custom',
                zh: '自定义',
            },
            sync_mode_custom_desc: {
                en: 'Pick individual settings to sync in a separate dialog.',
                zh: '在弹窗中自由选择需要同步的配置项。',
            },
            sync_mode_selective: {
                en: 'Cross-platform (exclude platform-specific settings)',
                zh: '跨平台（排除平台相关设置）',
            },
            sync_sections_title: { en: 'Sync settings', zh: '同步设置' },
            sync_sections_hint: {
                en: 'Cross-platform mode skips hotkeys, fonts, shell paths and other platform-specific items. Custom mode lets you pick each item.',
                zh: '跨平台模式会跳过热键、字体、shell 路径等平台相关项；自定义模式可逐项选择。',
            },
            manual_sync_title: { en: 'Choose sections to sync', zh: '选择本次同步范围' },
            manual_sync_confirm: { en: 'Start sync', zh: '开始同步' },
            custom_fields_title: { en: 'Custom sync items', zh: '自定义同步项' },
            custom_fields_hint: {
                en: 'Select which config fields should be included when using Custom mode.',
                zh: '选择在「自定义」模式下需要同步的配置项。',
            },
            configure_custom_items: { en: 'Configure sync items', zh: '配置同步项' },
            custom_fields_summary: {
                en: '{count} of {total} items selected',
                zh: '已选择 {count} / {total} 项',
            },
            save_sync_settings: { en: 'Save sync settings', zh: '保存同步设置' },
            sync_vault_title: { en: 'Sync Vault secrets', zh: '同步 Vault 密钥库' },
            sync_vault_hint_short: {
                en: 'Master password is never uploaded to the cloud.',
                zh: '主密码不会上传到云端。',
            },
            sync_vault_scope_note: {
                en: 'If encrypted config is enabled, all settings are stored in Vault and are decrypted automatically for selective sync — this toggle is not required. When config is not encrypted, enable this to sync SSH passwords and other secrets in vault.secrets.',
                zh: '若已开启「加密配置文件」，所有设置均在 Vault 内，同步时会自动解密并参与选择性同步，无需开启此开关。若未加密配置文件，开启此开关才会同步 vault.secrets 中的 SSH 密码等密钥。',
            },
            sync_vault_details: {
                en: 'Applies only when config is not encrypted. Use the same Vault master password on all devices. On conflict the whole secrets store is replaced — avoid editing secrets on two machines at once. Enable Vault under Tabby Settings → Security and save SSH passwords there first.',
                zh: '仅在未开启「加密配置文件」时生效。所有设备须使用相同 Vault 主密码。冲突时整库覆盖，请勿同时在两台机器修改密钥。请先在 Tabby「设置 → 安全」启用 Vault 并保存 SSH 密码。',
            },
            encrypted_config_warning: {
                en: 'Encrypted config detected on this device or in the cloud. Sync decrypts vault data with your master password, merges settings, then saves in your local format (encrypted or plain).',
                zh: '检测到本机或云端使用了加密配置。同步时会用 Vault 主密码解密、合并设置，再按本机格式（加密或明文）保存。',
            },
            vault_passphrase_required: {
                en: 'Vault master password is required to decrypt encrypted config. Enable Vault in Tabby Settings → Security, or enter the password when prompted.',
                zh: '解密加密配置需要 Vault 主密码。请在 Tabby「设置 → 安全」启用 Vault，或在提示时输入密码。',
            },
            vault_decrypt_failed: {
                en: 'Failed to decrypt Vault secrets. Use the same Vault master password on all devices and re-sync.',
                zh: '无法解密 Vault 密钥。请确保所有设备使用相同的 Vault 主密码后重新同步。',
            },
            cloud_decrypt_empty: {
                en: 'Cloud config could not be decrypted (empty result). Check plugin version and cloud file integrity.',
                zh: '云端配置解密失败（结果为空），请检查插件版本与云端文件是否完整。',
            },
            cloud_config_empty: {
                en: 'Cloud config envelope has no config data. Re-upload from the device that has your settings.',
                zh: '云端配置包内没有有效配置数据，请在有完整设置的设备上重新上传。',
            },
            empty_merge_rejected: {
                en: 'Refusing to apply sync: merged config would be empty. Check Vault password and cloud file.',
                zh: '拒绝写入：合并结果为空。请检查 Vault 主密码与云端配置文件。',
            },
            empty_profiles_rejected: {
                en: 'Refusing to apply sync: merged config has no connection profiles. Check Vault password matches the uploading device.',
                zh: '拒绝写入：合并结果中没有连接配置。请确认 Vault 主密码与上传端设备一致。',
            },
            keychain_password_warning: {
                en: 'SSH passwords saved to the system keychain cannot be synced. Open each profile, click "Set password", and save the password to Tabby Vault. Then enable "Sync Vault secrets" below and re-sync.',
                zh: '保存在系统钥匙串的 SSH 密码无法同步。请打开各连接配置，点击「设置密码」存入 Tabby Vault，再开启下方「同步 Vault 密钥库」并重新同步。',
            },
        },
        pages: {
            feedback_title: { en: 'Feedback', zh: '反馈' },
            feedback_desc: {
                en: 'Report bugs or request features on GitHub Issues.',
                zh: '在 GitHub Issues 提交问题或功能建议。',
            },
            feedback_btn: { en: 'Open GitHub Issues', zh: '打开 GitHub Issues' },
            changelog_title: { en: 'Change log', zh: '更新日志' },
            changelog_desc: {
                en: 'Release history for tabby-sync-selective.',
                zh: 'tabby-sync-selective 版本更新记录。',
            },
            updates_title: { en: 'Check for updates', zh: '检查更新' },
            updates_current: { en: 'Current version', zh: '当前版本' },
            updates_check_btn: { en: 'Check npm registry', zh: '检查 npm 更新' },
            updates_latest: { en: 'Latest version on npm', zh: 'npm 最新版本' },
            updates_up_to_date: { en: 'You are on the latest version.', zh: '已是最新版本。' },
            updates_available: { en: 'A newer version is available. Update via Tabby Settings → Plugins.', zh: '有新版本可用，请在 Tabby「设置 → 插件」中更新。' },
            updates_error: { en: 'Failed to check updates. Try again later.', zh: '检查更新失败，请稍后再试。' },
            updates_processing: { en: 'Checking...', zh: '检查中...' },
        },
        log: {
            invalid_cloud_settings: 'Invalid cloud settings syncing',
            read_cloud_settings: 'Reading cloud settings',
            error_upload_settings: 'Upload settings file from local',
            error_test_connection: 'Connection error.',
        },
        s3: {
            title: 'Enter your AppID and Secret token',
            title_blackblaze: 'Enter your KeyID and Application Key',
            app_id_placeholder: 'Application Id',
            app_secret_placeholder: 'Application Secret',
            blackblaze_key_placeholder: 'Your Key ID',
            blackblaze_app_key_placeholder: 'Your Application Key Id',
            bucket_placeholder: 'Bucket',
            region_placeholder: 'Default region (optional)',
            blackblaze_bucket_placeholder: 'Enter your BlackBlaze B2 region',
            endpoint_placeholder: 'Endpoint URL',
            location_placeholder: 'Location /',
        },
        ftp: {
            title: 'Enter your FTP login credentials',
            host_placeholder: 'Host',
            location_placeholder: 'Location /',
            username_placeholder: 'Username',
            password_placeholder: '******',
            port_placeholder: 'Port',
        },
        webdav: {
            title: 'Enter your WebDav login credentials',
            host_placeholder: 'Host',
            username_placeholder: 'Username or Email',
            password_placeholder: '******',
            port_placeholder: 'Port',
            location_placeholder: 'Location /',
        },
        gist: {
            title: "Enter your Gist credentials",
            name: 'Friendly name (optional)',
            id: 'Gist ID (Leave empty to create a new one)',
            token: 'Gist token',
            invalid_provider: 'Invalid service provider.',
            enter_id: 'Enter your Gist ID',
            error_create_gist: 'Unable to create new gist. Check your token permission!',
        },
        buttons: {
            sync_from_cloud: 'Sync Cloud Settings',
            sync_from_local: 'Upload Local Settings',
            check_update: 'Check for updates',
            yes: 'Yes',
            cancel: { en: 'Cancel', zh: '取消' },
            no: 'No',
            ok: { en: 'OK', zh: '确定' },
            view: 'View',
            test_connection: 'Test Connection',
            processing: 'Processing...',
            save_settings: 'Save This Setting',
            upload_settings: 'Upload Local Setting (Forced)',
            cloud_syncing_progress: 'Syncing with the cloud...',
            remove_saved_setting: 'Remove this setting',
        },
    },

    refreshLocale (platform: PlatformService, config?: ConfigService): void {
        currentIsZh = isChineseLocale(platform, config)
    },

    isChinese (): boolean {
        return currentIsZh
    },

    trans: (key: string, vars?: Record<string, string | number>): string => {
        let dict: any = CloudSyncLang.lang
        const objects = key.split('.')
        for (const i in objects) {
            if (typeof dict[objects[i]] !== 'undefined') {
                dict = dict[objects[i]]
            }
        }

        let text = ''
        if (typeof dict === 'string') {
            text = dict
        } else if (dict && typeof dict.en === 'string' && typeof dict.zh === 'string') {
            text = currentIsZh ? dict.zh : dict.en
        }

        if (vars) {
            for (const [name, value] of Object.entries(vars)) {
                text = text.replace(`{${name}}`, String(value))
            }
        }

        return text
    },
}

export default CloudSyncLang
